### ISSUE TITLE
程序编译错误

### ISSUE THREAD

**Issue by gzzz2008** [SmallPond/X-Knob#1]
程序编译总是错误，不知道怎么修改？小白，望指点。
另外说硬件去电电容就可以USB链接，具体要去掉哪两个电容呢？

**Comment by SmallPond** [comment]
能否给出编译错误信息呢，截图或粘贴信息？ 

电容是 C17 和 C18。

**Comment by gzzz2008** [comment]
编译错误图片。
![11111](https://user-images.githubusercontent.com/106231604/212806726-29012b55-b7ae-418b-97a9-4e60634ee002.jpg)

**Comment by gzzz2008** [comment]
怎么没有找到C17和C18呢？在哪块板子上呢？

**Comment by SmallPond** [comment]
> 编译错误图片。 ![11111](https://user-images.githubusercontent.com/106231604/212806726-29012b55-b7ae-418b-97a9-4e60634ee002.jpg)

应该是你 platformio 里的 ESP32 库版本太低了，还不支持esp32-s3开发板，如下图试试 5.2.0 或 4.4

![image](https://user-images.githubusercontent.com/21339153/212893284-7500ef39-bbfe-4163-8c80-01b7f57c1a18.png)



> 怎么没有找到C17和C18呢？在哪块板子上呢？是不是C7和C8呢？

在原理图上是 C17 和 C18，PCB 上的丝印是 C10 和 C11

**Comment by gzzz2008** [comment]
我看了一下ESp32的版本就是5.2.0啊。还有可能是其他的原因吗？

**Comment by gzzz2008** [comment]
![111111](https://user-images.githubusercontent.com/106231604/213048270-c8b21ac9-5ba9-4009-a642-2f380308ba50.jpg)
这是今天刚编译的，显示有这4处的错误。

**Comment by SmallPond** [comment]
可以参考一下我 README中新增的“编译问题”说明，确认.platformio\platforms\espressif32\platform.json 文件中版本是否正确。这个问题我之前也遇到过，我就是更新版本就可以了。

如果还不行，建议在 platformio 先完全卸载 esp32 库再装一遍。

**Comment by SmallPond** [comment]
另一个确认点是看 `./platformio/packages/framework-arduinoespressif32/tools/sdk/` 目录下是否有 `esp32s3/` 目录。

**Comment by gzzz2008** [comment]
![111111](https://user-images.githubusercontent.com/106231604/213114555-9556a02c-a746-47f9-9eba-2f47cb62587a.jpg)
重新删除安装了一下，又出现这样的错误。

**Comment by gzzz2008** [comment]
一定要编译吗？有没有封装好的，直接下载呢？

**Comment by SmallPond** [comment]
不知道是否是你的中文路径有影响。这到了链接过程了，很好解决的，你可以试着自己解决一下。



> 一定要编译吗？有没有封装好的，直接下载呢？

我晚点发一个 release 吧。
