### ISSUE TITLE
Error: Unknown board ID 'esp32-s3-devkitc-1'

### ISSUE THREAD

**Issue by Bing-Study** [SmallPond/X-Knob#10]
使用的的45君的硬件，为什么使用platform编译会出现这种错误

**Comment by SmallPond** [comment]
贴下详细保存的截图呢，大概率是pio版本不对

**Comment by Bing-Study** [comment]
![image](https://github.com/SmallPond/X-Knob/assets/61307265/5a81443a-abe1-4d4c-905f-5aed823d8cf4)

**Comment by SmallPond** [comment]
嗯...你贴的信息没有pio版本和arduino版本信息。  应该主要是这个问题，你可以更新到最新试试。
