### ISSUE TITLE
对于ESP32芯片的代码来说需要修改那些地方呢？

### ISSUE THREAD

**Issue by xxjerryxx1014** [SmallPond/X-Knob#17]
我做了一个是用ESP32芯片的，然后烧录的时候就报错了A fatal error occurred: This chip is ESP32 not ESP32-S3. Wrong --chip argument?，请问可以修改成针对此芯片的程序吗？

**Comment by SmallPond** [comment]
可以修改，在 platformio.ini 文件中修改对对应的芯片就行。 但是引脚等相关配置你都需要再适配一下。
