### ISSUE TITLE
l老哥，嘉立创开源的那个是最新版的吗？那个bom能够直接用吗？

### ISSUE THREAD

**Issue by NereeScarlet** [SmallPond/X-Knob#2]
如题
看到hardware文件里面的文档说嘉立创那有开源
想要问一下能不能用那个BOM
另外那个BOM的KT-0603RKENTO C2286 立创商城里面好像没有了？

**Comment by NereeScarlet** [comment]
另外大佬pcb文件是哪个啊

**Comment by NereeScarlet** [comment]
大佬，驱动板和屏幕板嘉立创显示不是嘉立创eda绘制的，不能用每月两张的那个免费打样券QAQ

**Comment by NereeScarlet** [comment]
啊，解决了，只要在丝印那里随便加点啥就可以通过审核了。

**Comment by SmallPond** [comment]
> 如题
> 看到hardware文件里面的文档说嘉立创那有开源
> 想要问一下能不能用那个BOM
> 另外那个BOM的KT-0603RKENTO C2286 立创商城里面好像没有了？
> 
> 
> 

我就是用的那个开源方案和bom，应该是没问题的。

**Comment by NereeScarlet** [comment]
> > 如题
> > 看到hardware文件里面的文档说嘉立创那有开源
> > 想要问一下能不能用那个BOM
> > 另外那个BOM的KT-0603RKENTO C2286 立创商城里面好像没有了？
> 
> 我就是用的那个开源方案和bom，应该是没问题的。

多谢，我试试
