### ISSUE TITLE
创建.bin文件

### ISSUE THREAD

**Issue by Le-Duc0069** [SmallPond/X-Knob#21]
我真的很喜欢你们的产品，非常好，你们能帮我创建一个 .bin 文件，以便我可以将其烧录为 esp32 吗？

**Comment by SmallPond** [comment]
在 release 可以找到 bin 文件的

**Comment by Le-Duc0069** [comment]
能问一下那个文件在哪里吗？

**Comment by SmallPond** [comment]
https://github.com/SmallPond/X-Knob/releases

**Comment by Le-Duc0069** [comment]
如果我想控制家里的多个设备，有没有办法添加更多设备？

**Comment by SmallPond** [comment]
目前只能通过修改代码的方式，我已经封装好了函数，如果会的话增加起来很方便。 未来可能会增加网页配置方式。

**Comment by Le-Duc0069** [comment]
希望尽快发布网页版
